mapa_abrev_palav = {
    # Censura
    'cu': 'coi',
    'puta': 'póica',
    'crlh': 'baralho',
    'crl': 'baralho',
    'wpp': 'wow papi',
    "merda": "droga",
    "bosta": "porcaria",
    "caralho": "caramba",
    "porra": "poxa",
    "puto": "pupu",
    "buceta": "parte íntima",
    "xota": "parte íntima",
    "pau": "parte íntima",
    "pinto": "parte íntima",
    "piroca": "parte íntima",
    "piroka": "parte íntima",
    "pica": "parte íntima",
    "pika": "parte íntima",
    "cusão": "vacilão",
    "cuzão": "vacilão",
    "foder": "ferrar",
    "foda": "difícil",
    "foda-se": "deixa pra lá",
    "fodasse": "deixa pra lá",
    "fodace": "deixa pra lá",
    "caralhos": "coisas",
    "cacete": "caramba",
    "arrombado": "desgraçado",
    "desgraça": "coisa ruim",
    "piranha": "pessoa ruim",
    "vagabunda": "desocupada",
    "corno": "traído",
    "broxa": "fraco",
    "viado": "rapaz", 
    "veado": "rapaz", 
    "boquete": "bobo",
    "punheta": "5 contra 1",
    
    "matar": "desvivar",
    "morte": "falecimento",
    "morreu": "foi de base",
    "suicídio": "arrasta pra cima",
    "suicidio": "arrasta pra cima",
    "se matar": "ir de base",
    "droga": "to chi ku",
    "maconha": "erva",
    "cocaína": "farinha",
    "cocaina": "farinha",
    "estupro": "abuso",
    "assassinato": "crime",
    "sangue": "vermelho",
    "arma": "brinquedo",
    "tiro": "disparo",
    "nazista": "criminoso",
    "hitler": "o pintor austríaco",
    "pedofilia": "crime contra criança",
    "pornografia": "conteúdo adulto",
    "sexo": "nheco nheco", # Ou "relação"
    "nude": "foto",
    "pelado": "sem roupa",
    "pelada": "sem roupa",
    
    # Abreviacao
    'tbm': 'também',
    'abs': 'abraços',
    "mn": "mano",
    "blz": "beleza",
    "tm": "tamo",
    "pdc": "pode crer",
    "gnt": "gente",
    "mddc": "meu deus do céu",
    "plmdds": "pelo amor de deus",
    "sdds": "saudades",
    "sqn": "só que não",
    "slk": "cêé louco",
    "vdd": "verdade",
    "vd": "vida",
    "mlr": "melhor",
    "tlgd": "tá ligado",
    "pv": "privado",
    "plmns": "pelo menos",
    "ngc": "negócio",
    "vc": "você",
    "tb": "também",
    "fzr": "fazer",
    "dps": "depois",
    "ft": "foto",
    "fml": "família",
    "rlx": "relaxa",
    "fut": "futebol",
    "bj": "beijo",
    "ajd": "ajuda",
    "pls": "por favor",
    "obg": "obrigado", 
    "pq": "porque",
    "vlw": "valeu",
    "hrs": "horas",
    "nd": "nada",
    "pfv": "por favor",
    "att": "ah tá",
    "msm": "mesmo",
    "msg": "mensagem",
    "add": "adicionar",
    "amg": "amigo",
    "cmg": "comigo",
    "glr": "galera",
    "pprt": "papo reto",
    "cvs": "conversar",
    "ss": "sim",
    "qt": "quanto",
    "nn": "não",
    "clr": "celular",
    "sla": "sei lá",
    "qria": "queria",
    "qser": "quiser",
    "pft": "perfeito",
    "dnv": "de novo",
    "sm": "sem",
    "cm": "com",
    "vms": "vamos",
    "flw": "falou",
    "trd": "tarde",
    "aq": "aqui",
    "bnt": "bonito",
    "ngm": "ninguém"
        
}


extreme_bad = [
    
    'bolsonaro',
    'o lula',
    'do lula',
    'lule',
    'luli',
    'o lule',
    'o luli',
    'descondenado'

    
]